// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package events

import (
	"context"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/broker"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/clock"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/conf"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/outbox"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/postgres"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/redis"
	"github.com/AustinZhu/quantum/datafeed/internal/modules/ingestion/biz"
	"github.com/AustinZhu/quantum/datafeed/internal/modules/ingestion/data"
	biz2 "github.com/AustinZhu/quantum/datafeed/internal/modules/marketdata/biz"
	data3 "github.com/AustinZhu/quantum/datafeed/internal/modules/marketdata/data"
	biz3 "github.com/AustinZhu/quantum/datafeed/internal/modules/scanner/biz"
	data2 "github.com/AustinZhu/quantum/datafeed/internal/modules/scanner/data"
	"github.com/AustinZhu/quantum/datafeed/internal/modules/scanner/service"
)

// Injectors from wire.go:

func InitializeEventsApp(ctx context.Context, configPath string) (*App, func(), error) {
	config, err := conf.New(ctx, configPath)
	if err != nil {
		return nil, nil, err
	}
	commandConsumer, cleanup, err := broker.NewCommandConsumer(config)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := postgres.New(ctx, config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	outboxStore := postgres.NewOutboxStore(client)
	repository := data.NewRepository(client, outboxStore)
	v := clock.New()
	bizService := biz.NewService(repository, v)
	redisClient, cleanup3, err := redis.New(config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	publisher, cleanup4, err := broker.NewPublisher(config, redisClient)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	dataRepository := data2.NewRepository(client)
	queryRepository := data3.NewQueryRepository(client)
	marketProvider := data3.NewMarketProvider(config)
	service2 := biz2.NewService(queryRepository, marketProvider)
	service3 := biz3.NewService(dataRepository, service2)
	projectionUpdater := service.NewProjectionUpdater(service3)
	dispatcher := outbox.NewDispatcher(config, outboxStore, publisher, projectionUpdater, v)
	app := New(commandConsumer, bizService, dispatcher)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
