// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package biz

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// InsertNews provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertNews(ctx context.Context, item NewsEvent) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for InsertNews")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, NewsEvent) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_InsertNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertNews'
type MockRepository_InsertNews_Call struct {
	*mock.Call
}

// InsertNews is a helper method to define mock.On call
//   - ctx context.Context
//   - item NewsEvent
func (_e *MockRepository_Expecter) InsertNews(ctx interface{}, item interface{}) *MockRepository_InsertNews_Call {
	return &MockRepository_InsertNews_Call{Call: _e.mock.On("InsertNews", ctx, item)}
}

func (_c *MockRepository_InsertNews_Call) Run(run func(ctx context.Context, item NewsEvent)) *MockRepository_InsertNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 NewsEvent
		if args[1] != nil {
			arg1 = args[1].(NewsEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_InsertNews_Call) Return(err error) *MockRepository_InsertNews_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_InsertNews_Call) RunAndReturn(run func(ctx context.Context, item NewsEvent) error) *MockRepository_InsertNews_Call {
	_c.Call.Return(run)
	return _c
}

// InsertSocial provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertSocial(ctx context.Context, item SocialEvent) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for InsertSocial")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SocialEvent) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_InsertSocial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertSocial'
type MockRepository_InsertSocial_Call struct {
	*mock.Call
}

// InsertSocial is a helper method to define mock.On call
//   - ctx context.Context
//   - item SocialEvent
func (_e *MockRepository_Expecter) InsertSocial(ctx interface{}, item interface{}) *MockRepository_InsertSocial_Call {
	return &MockRepository_InsertSocial_Call{Call: _e.mock.On("InsertSocial", ctx, item)}
}

func (_c *MockRepository_InsertSocial_Call) Run(run func(ctx context.Context, item SocialEvent)) *MockRepository_InsertSocial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SocialEvent
		if args[1] != nil {
			arg1 = args[1].(SocialEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_InsertSocial_Call) Return(err error) *MockRepository_InsertSocial_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_InsertSocial_Call) RunAndReturn(run func(ctx context.Context, item SocialEvent) error) *MockRepository_InsertSocial_Call {
	_c.Call.Return(run)
	return _c
}

// ListNews provides a mock function for the type MockRepository
func (_mock *MockRepository) ListNews(ctx context.Context, symbol string, limit int32) ([]NewsEvent, error) {
	ret := _mock.Called(ctx, symbol, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListNews")
	}

	var r0 []NewsEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int32) ([]NewsEvent, error)); ok {
		return returnFunc(ctx, symbol, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int32) []NewsEvent); ok {
		r0 = returnFunc(ctx, symbol, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]NewsEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int32) error); ok {
		r1 = returnFunc(ctx, symbol, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNews'
type MockRepository_ListNews_Call struct {
	*mock.Call
}

// ListNews is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - limit int32
func (_e *MockRepository_Expecter) ListNews(ctx interface{}, symbol interface{}, limit interface{}) *MockRepository_ListNews_Call {
	return &MockRepository_ListNews_Call{Call: _e.mock.On("ListNews", ctx, symbol, limit)}
}

func (_c *MockRepository_ListNews_Call) Run(run func(ctx context.Context, symbol string, limit int32)) *MockRepository_ListNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_ListNews_Call) Return(newsEvents []NewsEvent, err error) *MockRepository_ListNews_Call {
	_c.Call.Return(newsEvents, err)
	return _c
}

func (_c *MockRepository_ListNews_Call) RunAndReturn(run func(ctx context.Context, symbol string, limit int32) ([]NewsEvent, error)) *MockRepository_ListNews_Call {
	_c.Call.Return(run)
	return _c
}

// ListSocial provides a mock function for the type MockRepository
func (_mock *MockRepository) ListSocial(ctx context.Context, symbol string, limit int32) ([]SocialEvent, error) {
	ret := _mock.Called(ctx, symbol, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListSocial")
	}

	var r0 []SocialEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int32) ([]SocialEvent, error)); ok {
		return returnFunc(ctx, symbol, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int32) []SocialEvent); ok {
		r0 = returnFunc(ctx, symbol, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SocialEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int32) error); ok {
		r1 = returnFunc(ctx, symbol, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListSocial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSocial'
type MockRepository_ListSocial_Call struct {
	*mock.Call
}

// ListSocial is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - limit int32
func (_e *MockRepository_Expecter) ListSocial(ctx interface{}, symbol interface{}, limit interface{}) *MockRepository_ListSocial_Call {
	return &MockRepository_ListSocial_Call{Call: _e.mock.On("ListSocial", ctx, symbol, limit)}
}

func (_c *MockRepository_ListSocial_Call) Run(run func(ctx context.Context, symbol string, limit int32)) *MockRepository_ListSocial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_ListSocial_Call) Return(socialEvents []SocialEvent, err error) *MockRepository_ListSocial_Call {
	_c.Call.Return(socialEvents, err)
	return _c
}

func (_c *MockRepository_ListSocial_Call) RunAndReturn(run func(ctx context.Context, symbol string, limit int32) ([]SocialEvent, error)) *MockRepository_ListSocial_Call {
	_c.Call.Return(run)
	return _c
}
