// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package biz

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockQueryRepository creates a new instance of MockQueryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryRepository {
	mock := &MockQueryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryRepository is an autogenerated mock type for the QueryRepository type
type MockQueryRepository struct {
	mock.Mock
}

type MockQueryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryRepository) EXPECT() *MockQueryRepository_Expecter {
	return &MockQueryRepository_Expecter{mock: &_m.Mock}
}

// QueryBars provides a mock function for the type MockQueryRepository
func (_mock *MockQueryRepository) QueryBars(ctx context.Context, symbol string, interval string, startMS int64, endMS int64, limit int32) ([]Bar, error) {
	ret := _mock.Called(ctx, symbol, interval, startMS, endMS, limit)

	if len(ret) == 0 {
		panic("no return value specified for QueryBars")
	}

	var r0 []Bar
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, int64, int32) ([]Bar, error)); ok {
		return returnFunc(ctx, symbol, interval, startMS, endMS, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, int64, int32) []Bar); ok {
		r0 = returnFunc(ctx, symbol, interval, startMS, endMS, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Bar)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64, int64, int32) error); ok {
		r1 = returnFunc(ctx, symbol, interval, startMS, endMS, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryRepository_QueryBars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryBars'
type MockQueryRepository_QueryBars_Call struct {
	*mock.Call
}

// QueryBars is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - interval string
//   - startMS int64
//   - endMS int64
//   - limit int32
func (_e *MockQueryRepository_Expecter) QueryBars(ctx interface{}, symbol interface{}, interval interface{}, startMS interface{}, endMS interface{}, limit interface{}) *MockQueryRepository_QueryBars_Call {
	return &MockQueryRepository_QueryBars_Call{Call: _e.mock.On("QueryBars", ctx, symbol, interval, startMS, endMS, limit)}
}

func (_c *MockQueryRepository_QueryBars_Call) Run(run func(ctx context.Context, symbol string, interval string, startMS int64, endMS int64, limit int32)) *MockQueryRepository_QueryBars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 int32
		if args[5] != nil {
			arg5 = args[5].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockQueryRepository_QueryBars_Call) Return(bars []Bar, err error) *MockQueryRepository_QueryBars_Call {
	_c.Call.Return(bars, err)
	return _c
}

func (_c *MockQueryRepository_QueryBars_Call) RunAndReturn(run func(ctx context.Context, symbol string, interval string, startMS int64, endMS int64, limit int32) ([]Bar, error)) *MockQueryRepository_QueryBars_Call {
	_c.Call.Return(run)
	return _c
}

// ReplayTicks provides a mock function for the type MockQueryRepository
func (_mock *MockQueryRepository) ReplayTicks(ctx context.Context, symbol string, startMS int64, endMS int64, limit int32) ([]Tick, error) {
	ret := _mock.Called(ctx, symbol, startMS, endMS, limit)

	if len(ret) == 0 {
		panic("no return value specified for ReplayTicks")
	}

	var r0 []Tick
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64, int32) ([]Tick, error)); ok {
		return returnFunc(ctx, symbol, startMS, endMS, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64, int32) []Tick); ok {
		r0 = returnFunc(ctx, symbol, startMS, endMS, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Tick)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64, int32) error); ok {
		r1 = returnFunc(ctx, symbol, startMS, endMS, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryRepository_ReplayTicks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplayTicks'
type MockQueryRepository_ReplayTicks_Call struct {
	*mock.Call
}

// ReplayTicks is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - startMS int64
//   - endMS int64
//   - limit int32
func (_e *MockQueryRepository_Expecter) ReplayTicks(ctx interface{}, symbol interface{}, startMS interface{}, endMS interface{}, limit interface{}) *MockQueryRepository_ReplayTicks_Call {
	return &MockQueryRepository_ReplayTicks_Call{Call: _e.mock.On("ReplayTicks", ctx, symbol, startMS, endMS, limit)}
}

func (_c *MockQueryRepository_ReplayTicks_Call) Run(run func(ctx context.Context, symbol string, startMS int64, endMS int64, limit int32)) *MockQueryRepository_ReplayTicks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 int32
		if args[4] != nil {
			arg4 = args[4].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockQueryRepository_ReplayTicks_Call) Return(ticks []Tick, err error) *MockQueryRepository_ReplayTicks_Call {
	_c.Call.Return(ticks, err)
	return _c
}

func (_c *MockQueryRepository_ReplayTicks_Call) RunAndReturn(run func(ctx context.Context, symbol string, startMS int64, endMS int64, limit int32) ([]Tick, error)) *MockQueryRepository_ReplayTicks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMarketProvider creates a new instance of MockMarketProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMarketProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMarketProvider {
	mock := &MockMarketProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMarketProvider is an autogenerated mock type for the MarketProvider type
type MockMarketProvider struct {
	mock.Mock
}

type MockMarketProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMarketProvider) EXPECT() *MockMarketProvider_Expecter {
	return &MockMarketProvider_Expecter{mock: &_m.Mock}
}

// GetHistoryCandles provides a mock function for the type MockMarketProvider
func (_mock *MockMarketProvider) GetHistoryCandles(ctx context.Context, symbol string, resolution string, fromSec int64, toSec int64, countback uint32) ([]Candle, error) {
	ret := _mock.Called(ctx, symbol, resolution, fromSec, toSec, countback)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoryCandles")
	}

	var r0 []Candle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, int64, uint32) ([]Candle, error)); ok {
		return returnFunc(ctx, symbol, resolution, fromSec, toSec, countback)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, int64, uint32) []Candle); ok {
		r0 = returnFunc(ctx, symbol, resolution, fromSec, toSec, countback)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Candle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64, int64, uint32) error); ok {
		r1 = returnFunc(ctx, symbol, resolution, fromSec, toSec, countback)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarketProvider_GetHistoryCandles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistoryCandles'
type MockMarketProvider_GetHistoryCandles_Call struct {
	*mock.Call
}

// GetHistoryCandles is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - resolution string
//   - fromSec int64
//   - toSec int64
//   - countback uint32
func (_e *MockMarketProvider_Expecter) GetHistoryCandles(ctx interface{}, symbol interface{}, resolution interface{}, fromSec interface{}, toSec interface{}, countback interface{}) *MockMarketProvider_GetHistoryCandles_Call {
	return &MockMarketProvider_GetHistoryCandles_Call{Call: _e.mock.On("GetHistoryCandles", ctx, symbol, resolution, fromSec, toSec, countback)}
}

func (_c *MockMarketProvider_GetHistoryCandles_Call) Run(run func(ctx context.Context, symbol string, resolution string, fromSec int64, toSec int64, countback uint32)) *MockMarketProvider_GetHistoryCandles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 uint32
		if args[5] != nil {
			arg5 = args[5].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockMarketProvider_GetHistoryCandles_Call) Return(candles []Candle, err error) *MockMarketProvider_GetHistoryCandles_Call {
	_c.Call.Return(candles, err)
	return _c
}

func (_c *MockMarketProvider_GetHistoryCandles_Call) RunAndReturn(run func(ctx context.Context, symbol string, resolution string, fromSec int64, toSec int64, countback uint32) ([]Candle, error)) *MockMarketProvider_GetHistoryCandles_Call {
	_c.Call.Return(run)
	return _c
}

// GetTickers provides a mock function for the type MockMarketProvider
func (_mock *MockMarketProvider) GetTickers(ctx context.Context, symbols []string) ([]Ticker, error) {
	ret := _mock.Called(ctx, symbols)

	if len(ret) == 0 {
		panic("no return value specified for GetTickers")
	}

	var r0 []Ticker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]Ticker, error)); ok {
		return returnFunc(ctx, symbols)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []Ticker); ok {
		r0 = returnFunc(ctx, symbols)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Ticker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, symbols)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarketProvider_GetTickers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTickers'
type MockMarketProvider_GetTickers_Call struct {
	*mock.Call
}

// GetTickers is a helper method to define mock.On call
//   - ctx context.Context
//   - symbols []string
func (_e *MockMarketProvider_Expecter) GetTickers(ctx interface{}, symbols interface{}) *MockMarketProvider_GetTickers_Call {
	return &MockMarketProvider_GetTickers_Call{Call: _e.mock.On("GetTickers", ctx, symbols)}
}

func (_c *MockMarketProvider_GetTickers_Call) Run(run func(ctx context.Context, symbols []string)) *MockMarketProvider_GetTickers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMarketProvider_GetTickers_Call) Return(tickers []Ticker, err error) *MockMarketProvider_GetTickers_Call {
	_c.Call.Return(tickers, err)
	return _c
}

func (_c *MockMarketProvider_GetTickers_Call) RunAndReturn(run func(ctx context.Context, symbols []string) ([]Ticker, error)) *MockMarketProvider_GetTickers_Call {
	_c.Call.Return(run)
	return _c
}

// ListSymbols provides a mock function for the type MockMarketProvider
func (_mock *MockMarketProvider) ListSymbols(ctx context.Context) ([]Symbol, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSymbols")
	}

	var r0 []Symbol
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]Symbol, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Symbol); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Symbol)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarketProvider_ListSymbols_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSymbols'
type MockMarketProvider_ListSymbols_Call struct {
	*mock.Call
}

// ListSymbols is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMarketProvider_Expecter) ListSymbols(ctx interface{}) *MockMarketProvider_ListSymbols_Call {
	return &MockMarketProvider_ListSymbols_Call{Call: _e.mock.On("ListSymbols", ctx)}
}

func (_c *MockMarketProvider_ListSymbols_Call) Run(run func(ctx context.Context)) *MockMarketProvider_ListSymbols_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMarketProvider_ListSymbols_Call) Return(symbols []Symbol, err error) *MockMarketProvider_ListSymbols_Call {
	_c.Call.Return(symbols, err)
	return _c
}

func (_c *MockMarketProvider_ListSymbols_Call) RunAndReturn(run func(ctx context.Context) ([]Symbol, error)) *MockMarketProvider_ListSymbols_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeBars provides a mock function for the type MockMarketProvider
func (_mock *MockMarketProvider) SubscribeBars(ctx context.Context, symbol string, resolution string) (<-chan Candle, <-chan error, error) {
	ret := _mock.Called(ctx, symbol, resolution)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeBars")
	}

	var r0 <-chan Candle
	var r1 <-chan error
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (<-chan Candle, <-chan error, error)); ok {
		return returnFunc(ctx, symbol, resolution)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) <-chan Candle); ok {
		r0 = returnFunc(ctx, symbol, resolution)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan Candle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) <-chan error); ok {
		r1 = returnFunc(ctx, symbol, resolution)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, symbol, resolution)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMarketProvider_SubscribeBars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeBars'
type MockMarketProvider_SubscribeBars_Call struct {
	*mock.Call
}

// SubscribeBars is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - resolution string
func (_e *MockMarketProvider_Expecter) SubscribeBars(ctx interface{}, symbol interface{}, resolution interface{}) *MockMarketProvider_SubscribeBars_Call {
	return &MockMarketProvider_SubscribeBars_Call{Call: _e.mock.On("SubscribeBars", ctx, symbol, resolution)}
}

func (_c *MockMarketProvider_SubscribeBars_Call) Run(run func(ctx context.Context, symbol string, resolution string)) *MockMarketProvider_SubscribeBars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMarketProvider_SubscribeBars_Call) Return(candleCh <-chan Candle, errCh <-chan error, err error) *MockMarketProvider_SubscribeBars_Call {
	_c.Call.Return(candleCh, errCh, err)
	return _c
}

func (_c *MockMarketProvider_SubscribeBars_Call) RunAndReturn(run func(ctx context.Context, symbol string, resolution string) (<-chan Candle, <-chan error, error)) *MockMarketProvider_SubscribeBars_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeTicks provides a mock function for the type MockMarketProvider
func (_mock *MockMarketProvider) SubscribeTicks(ctx context.Context, symbol string) (<-chan Ticker, <-chan error, error) {
	ret := _mock.Called(ctx, symbol)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeTicks")
	}

	var r0 <-chan Ticker
	var r1 <-chan error
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (<-chan Ticker, <-chan error, error)); ok {
		return returnFunc(ctx, symbol)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) <-chan Ticker); ok {
		r0 = returnFunc(ctx, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan Ticker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) <-chan error); ok {
		r1 = returnFunc(ctx, symbol)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, symbol)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMarketProvider_SubscribeTicks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeTicks'
type MockMarketProvider_SubscribeTicks_Call struct {
	*mock.Call
}

// SubscribeTicks is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
func (_e *MockMarketProvider_Expecter) SubscribeTicks(ctx interface{}, symbol interface{}) *MockMarketProvider_SubscribeTicks_Call {
	return &MockMarketProvider_SubscribeTicks_Call{Call: _e.mock.On("SubscribeTicks", ctx, symbol)}
}

func (_c *MockMarketProvider_SubscribeTicks_Call) Run(run func(ctx context.Context, symbol string)) *MockMarketProvider_SubscribeTicks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMarketProvider_SubscribeTicks_Call) Return(tickerCh <-chan Ticker, errCh <-chan error, err error) *MockMarketProvider_SubscribeTicks_Call {
	_c.Call.Return(tickerCh, errCh, err)
	return _c
}

func (_c *MockMarketProvider_SubscribeTicks_Call) RunAndReturn(run func(ctx context.Context, symbol string) (<-chan Ticker, <-chan error, error)) *MockMarketProvider_SubscribeTicks_Call {
	_c.Call.Return(run)
	return _c
}
