// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package biz

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// InsertTicksAndEvents provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertTicksAndEvents(ctx context.Context, ticks []Tick, events []EventRecord) error {
	ret := _mock.Called(ctx, ticks, events)

	if len(ret) == 0 {
		panic("no return value specified for InsertTicksAndEvents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []Tick, []EventRecord) error); ok {
		r0 = returnFunc(ctx, ticks, events)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_InsertTicksAndEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTicksAndEvents'
type MockRepository_InsertTicksAndEvents_Call struct {
	*mock.Call
}

// InsertTicksAndEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - ticks []Tick
//   - events []EventRecord
func (_e *MockRepository_Expecter) InsertTicksAndEvents(ctx interface{}, ticks interface{}, events interface{}) *MockRepository_InsertTicksAndEvents_Call {
	return &MockRepository_InsertTicksAndEvents_Call{Call: _e.mock.On("InsertTicksAndEvents", ctx, ticks, events)}
}

func (_c *MockRepository_InsertTicksAndEvents_Call) Run(run func(ctx context.Context, ticks []Tick, events []EventRecord)) *MockRepository_InsertTicksAndEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []Tick
		if args[1] != nil {
			arg1 = args[1].([]Tick)
		}
		var arg2 []EventRecord
		if args[2] != nil {
			arg2 = args[2].([]EventRecord)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_InsertTicksAndEvents_Call) Return(err error) *MockRepository_InsertTicksAndEvents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_InsertTicksAndEvents_Call) RunAndReturn(run func(ctx context.Context, ticks []Tick, events []EventRecord) error) *MockRepository_InsertTicksAndEvents_Call {
	_c.Call.Return(run)
	return _c
}
