// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package simulator

import (
	"github.com/AustinZhu/quantum/datafeed/internal/modules/ingestion/biz"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTickSource creates a new instance of MockTickSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTickSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTickSource {
	mock := &MockTickSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTickSource is an autogenerated mock type for the TickSource type
type MockTickSource struct {
	mock.Mock
}

type MockTickSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTickSource) EXPECT() *MockTickSource_Expecter {
	return &MockTickSource_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockTickSource
func (_mock *MockTickSource) Generate(symbol string, count int) []biz.Tick {
	ret := _mock.Called(symbol, count)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 []biz.Tick
	if returnFunc, ok := ret.Get(0).(func(string, int) []biz.Tick); ok {
		r0 = returnFunc(symbol, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]biz.Tick)
		}
	}
	return r0
}

// MockTickSource_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockTickSource_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - symbol string
//   - count int
func (_e *MockTickSource_Expecter) Generate(symbol interface{}, count interface{}) *MockTickSource_Generate_Call {
	return &MockTickSource_Generate_Call{Call: _e.mock.On("Generate", symbol, count)}
}

func (_c *MockTickSource_Generate_Call) Run(run func(symbol string, count int)) *MockTickSource_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTickSource_Generate_Call) Return(ticks []biz.Tick) *MockTickSource_Generate_Call {
	_c.Call.Return(ticks)
	return _c
}

func (_c *MockTickSource_Generate_Call) RunAndReturn(run func(symbol string, count int) []biz.Tick) *MockTickSource_Generate_Call {
	_c.Call.Return(run)
	return _c
}
