// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DatafeedBars1m struct {
	Symbol   string
	Interval string
	TsMs     int64
	Open     float64
	High     float64
	Low      float64
	Close    float64
	Volume   float64
}

type DatafeedBars5m struct {
	Symbol   string
	Interval string
	TsMs     int64
	Open     float64
	High     float64
	Low      float64
	Close    float64
	Volume   float64
}

type DatafeedIngestOffset struct {
	Source       string
	PartitionKey string
	OffsetValue  string
	UpdatedAt    pgtype.Timestamptz
}

type DatafeedNewsEvent struct {
	ID        string
	Symbol    string
	Title     string
	Url       string
	TsMs      int64
	Source    string
	CreatedAt pgtype.Timestamptz
}

type DatafeedOutboxEvent struct {
	ID            string
	AggregateType string
	AggregateID   string
	EventType     string
	EventVersion  int32
	Payload       []byte
	Status        string
	RetryCount    int32
	NextRetryAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
	LastError     string
}

type DatafeedProcessedEvent struct {
	EventID      string
	ConsumerName string
	ProcessedAt  pgtype.Timestamptz
}

type DatafeedScannerSymbol struct {
	Symbol      string
	Ticker      string
	Description string
	Exchange    string
	Type        string
	State       string
	InstType    string
	UpdatedAt   pgtype.Timestamptz
}

type DatafeedSocialEvent struct {
	ID        string
	Symbol    string
	Platform  string
	Author    string
	Text      string
	TsMs      int64
	Sentiment float64
	CreatedAt pgtype.Timestamptz
}

type DatafeedTick struct {
	Symbol    string
	TsMs      int64
	Price     float64
	Size      float64
	Source    string
	CreatedAt pgtype.Timestamptz
}
