// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: ticks.sql

package db

import (
	"context"
)

const insertNewsEvent = `-- name: InsertNewsEvent :exec
INSERT INTO datafeed.news_events (id, symbol, title, url, ts_ms, source)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO NOTHING
`

type InsertNewsEventParams struct {
	ID     string
	Symbol string
	Title  string
	Url    string
	TsMs   int64
	Source string
}

func (q *Queries) InsertNewsEvent(ctx context.Context, arg InsertNewsEventParams) error {
	_, err := q.db.Exec(ctx, insertNewsEvent,
		arg.ID,
		arg.Symbol,
		arg.Title,
		arg.Url,
		arg.TsMs,
		arg.Source,
	)
	return err
}

const insertSocialEvent = `-- name: InsertSocialEvent :exec
INSERT INTO datafeed.social_events (id, symbol, platform, author, text, ts_ms, sentiment)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO NOTHING
`

type InsertSocialEventParams struct {
	ID        string
	Symbol    string
	Platform  string
	Author    string
	Text      string
	TsMs      int64
	Sentiment float64
}

func (q *Queries) InsertSocialEvent(ctx context.Context, arg InsertSocialEventParams) error {
	_, err := q.db.Exec(ctx, insertSocialEvent,
		arg.ID,
		arg.Symbol,
		arg.Platform,
		arg.Author,
		arg.Text,
		arg.TsMs,
		arg.Sentiment,
	)
	return err
}

const insertTick = `-- name: InsertTick :exec
INSERT INTO datafeed.ticks (symbol, ts_ms, price, size, source)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (symbol, ts_ms, source) DO UPDATE
SET price = EXCLUDED.price,
    size = EXCLUDED.size
`

type InsertTickParams struct {
	Symbol string
	TsMs   int64
	Price  float64
	Size   float64
	Source string
}

func (q *Queries) InsertTick(ctx context.Context, arg InsertTickParams) error {
	_, err := q.db.Exec(ctx, insertTick,
		arg.Symbol,
		arg.TsMs,
		arg.Price,
		arg.Size,
		arg.Source,
	)
	return err
}

const listBarsByRange = `-- name: ListBarsByRange :many
SELECT symbol, interval, ts_ms, open, high, low, close, volume
FROM datafeed.bars_1m
WHERE symbol = $1
  AND ts_ms >= $2
  AND ts_ms <= $3
ORDER BY ts_ms ASC
LIMIT $4
`

type ListBarsByRangeParams struct {
	Symbol string
	TsMs   int64
	TsMs_2 int64
	Limit  int32
}

func (q *Queries) ListBarsByRange(ctx context.Context, arg ListBarsByRangeParams) ([]DatafeedBars1m, error) {
	rows, err := q.db.Query(ctx, listBarsByRange,
		arg.Symbol,
		arg.TsMs,
		arg.TsMs_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DatafeedBars1m
	for rows.Next() {
		var i DatafeedBars1m
		if err := rows.Scan(
			&i.Symbol,
			&i.Interval,
			&i.TsMs,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicksByRange = `-- name: ListTicksByRange :many
SELECT symbol, ts_ms, price, size, source
FROM datafeed.ticks
WHERE symbol = $1
  AND ts_ms >= $2
  AND ts_ms <= $3
ORDER BY ts_ms ASC
LIMIT $4
`

type ListTicksByRangeParams struct {
	Symbol string
	TsMs   int64
	TsMs_2 int64
	Limit  int32
}

type ListTicksByRangeRow struct {
	Symbol string
	TsMs   int64
	Price  float64
	Size   float64
	Source string
}

func (q *Queries) ListTicksByRange(ctx context.Context, arg ListTicksByRangeParams) ([]ListTicksByRangeRow, error) {
	rows, err := q.db.Query(ctx, listTicksByRange,
		arg.Symbol,
		arg.TsMs,
		arg.TsMs_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicksByRangeRow
	for rows.Next() {
		var i ListTicksByRangeRow
		if err := rows.Scan(
			&i.Symbol,
			&i.TsMs,
			&i.Price,
			&i.Size,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
