http:
  enabled: true
  address: "0.0.0.0:4195"

logger:
  level: INFO
  format: logfmt

input:
  kafka_franz:
    seed_brokers:
      - redpanda:9092
    topics:
      - datafeed.ticks
    consumer_group: quantum-redpanda-connect

pipeline:
  processors:
    - mapping: |
        let parsed = content().parse_json().catch({})
        root = if $parsed != {} { $parsed } else { {"raw": content().string()} }
        root.stream_processed_at = now()
        root.stream_processor = "redpanda-connect"

output:
  kafka_franz:
    seed_brokers:
      - redpanda:9092
    topic: datafeed.ticks.enriched
