// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package jobs

import (
	"context"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/broker"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/clock"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/conf"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/outbox"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/postgres"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/redis"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/temporal"
	biz3 "github.com/AustinZhu/quantum/datafeed/internal/modules/jobs/biz"
	service2 "github.com/AustinZhu/quantum/datafeed/internal/modules/jobs/service"
	"github.com/AustinZhu/quantum/datafeed/internal/modules/marketdata/biz"
	data2 "github.com/AustinZhu/quantum/datafeed/internal/modules/marketdata/data"
	biz2 "github.com/AustinZhu/quantum/datafeed/internal/modules/scanner/biz"
	"github.com/AustinZhu/quantum/datafeed/internal/modules/scanner/data"
	"github.com/AustinZhu/quantum/datafeed/internal/modules/scanner/service"
)

// Injectors from wire.go:

func InitializeJobsApp(ctx context.Context, configPath string) (*App, func(), error) {
	config, err := conf.Provide(ctx, configPath)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup, err := postgres.New(ctx, config)
	if err != nil {
		return nil, nil, err
	}
	repository := data.NewRepository(client)
	queryRepository := data2.NewQueryRepository(client)
	marketProvider := data2.NewMarketProvider(config)
	bizService := biz.NewService(queryRepository, marketProvider)
	service3 := biz2.NewService(repository, bizService)
	outboxStore := postgres.NewOutboxStore(client)
	redisClient, cleanup2, err := redis.New(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	publisher, cleanup3, err := broker.NewPublisher(config, redisClient)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	projectionUpdater := service.NewProjectionUpdater(service3)
	clockClock := clock.New()
	dispatcher := outbox.NewDispatcher(config, outboxStore, publisher, projectionUpdater, clockClock)
	service4 := biz3.NewService(service3, dispatcher)
	syncMarketSymbolsTask := service2.NewSyncMarketSymbolsTask(config, service4)
	outboxRecoveryTask := service2.NewOutboxRecoveryTask(config, service4)
	rebuildScannerProjectionTask := service2.NewRebuildScannerProjectionTask(config, service4)
	marketBackfillTask := service2.NewMarketBackfillTask(config, service4)
	v := service2.ProvideTasks(syncMarketSymbolsTask, outboxRecoveryTask, rebuildScannerProjectionTask, marketBackfillTask)
	runner := temporal.NewRunner(config, v)
	app := New(runner)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
