run:
  timeout: 5m
  tests: true
linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
issues:
  exclude-dirs:
    - internal/gen
  max-issues-per-linter: 0
  max-same-issues: 0
