all: false
dir: "{{.InterfaceDir}}"
filename: "mocks_test.go"
force-file-write: true
formatter: goimports
pkgname: "{{.SrcPackageName}}"
structname: "{{.Mock}}{{.InterfaceName}}"
template: testify
packages:
  github.com/AustinZhu/quantum/datafeed/internal/modules:
    config:
      all: true
      recursive: true
