// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package biz

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// HasProcessedEvent provides a mock function for the type MockRepository
func (_mock *MockRepository) HasProcessedEvent(ctx context.Context, eventID string, consumer string) (bool, error) {
	ret := _mock.Called(ctx, eventID, consumer)

	if len(ret) == 0 {
		panic("no return value specified for HasProcessedEvent")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, eventID, consumer)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, eventID, consumer)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, eventID, consumer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_HasProcessedEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasProcessedEvent'
type MockRepository_HasProcessedEvent_Call struct {
	*mock.Call
}

// HasProcessedEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - consumer string
func (_e *MockRepository_Expecter) HasProcessedEvent(ctx interface{}, eventID interface{}, consumer interface{}) *MockRepository_HasProcessedEvent_Call {
	return &MockRepository_HasProcessedEvent_Call{Call: _e.mock.On("HasProcessedEvent", ctx, eventID, consumer)}
}

func (_c *MockRepository_HasProcessedEvent_Call) Run(run func(ctx context.Context, eventID string, consumer string)) *MockRepository_HasProcessedEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_HasProcessedEvent_Call) Return(b bool, err error) *MockRepository_HasProcessedEvent_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_HasProcessedEvent_Call) RunAndReturn(run func(ctx context.Context, eventID string, consumer string) (bool, error)) *MockRepository_HasProcessedEvent_Call {
	_c.Call.Return(run)
	return _c
}

// ListSymbols provides a mock function for the type MockRepository
func (_mock *MockRepository) ListSymbols(ctx context.Context) ([]Symbol, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSymbols")
	}

	var r0 []Symbol
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]Symbol, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Symbol); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Symbol)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListSymbols_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSymbols'
type MockRepository_ListSymbols_Call struct {
	*mock.Call
}

// ListSymbols is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListSymbols(ctx interface{}) *MockRepository_ListSymbols_Call {
	return &MockRepository_ListSymbols_Call{Call: _e.mock.On("ListSymbols", ctx)}
}

func (_c *MockRepository_ListSymbols_Call) Run(run func(ctx context.Context)) *MockRepository_ListSymbols_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_ListSymbols_Call) Return(symbols []Symbol, err error) *MockRepository_ListSymbols_Call {
	_c.Call.Return(symbols, err)
	return _c
}

func (_c *MockRepository_ListSymbols_Call) RunAndReturn(run func(ctx context.Context) ([]Symbol, error)) *MockRepository_ListSymbols_Call {
	_c.Call.Return(run)
	return _c
}

// MarkProcessedEvent provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkProcessedEvent(ctx context.Context, eventID string, consumer string) error {
	ret := _mock.Called(ctx, eventID, consumer)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessedEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, eventID, consumer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkProcessedEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkProcessedEvent'
type MockRepository_MarkProcessedEvent_Call struct {
	*mock.Call
}

// MarkProcessedEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - consumer string
func (_e *MockRepository_Expecter) MarkProcessedEvent(ctx interface{}, eventID interface{}, consumer interface{}) *MockRepository_MarkProcessedEvent_Call {
	return &MockRepository_MarkProcessedEvent_Call{Call: _e.mock.On("MarkProcessedEvent", ctx, eventID, consumer)}
}

func (_c *MockRepository_MarkProcessedEvent_Call) Run(run func(ctx context.Context, eventID string, consumer string)) *MockRepository_MarkProcessedEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_MarkProcessedEvent_Call) Return(err error) *MockRepository_MarkProcessedEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkProcessedEvent_Call) RunAndReturn(run func(ctx context.Context, eventID string, consumer string) error) *MockRepository_MarkProcessedEvent_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertSymbols provides a mock function for the type MockRepository
func (_mock *MockRepository) UpsertSymbols(ctx context.Context, items []Symbol) error {
	ret := _mock.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSymbols")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []Symbol) error); ok {
		r0 = returnFunc(ctx, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpsertSymbols_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertSymbols'
type MockRepository_UpsertSymbols_Call struct {
	*mock.Call
}

// UpsertSymbols is a helper method to define mock.On call
//   - ctx context.Context
//   - items []Symbol
func (_e *MockRepository_Expecter) UpsertSymbols(ctx interface{}, items interface{}) *MockRepository_UpsertSymbols_Call {
	return &MockRepository_UpsertSymbols_Call{Call: _e.mock.On("UpsertSymbols", ctx, items)}
}

func (_c *MockRepository_UpsertSymbols_Call) Run(run func(ctx context.Context, items []Symbol)) *MockRepository_UpsertSymbols_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []Symbol
		if args[1] != nil {
			arg1 = args[1].([]Symbol)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpsertSymbols_Call) Return(err error) *MockRepository_UpsertSymbols_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpsertSymbols_Call) RunAndReturn(run func(ctx context.Context, items []Symbol) error) *MockRepository_UpsertSymbols_Call {
	_c.Call.Return(run)
	return _c
}
