// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"context"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/auth"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/clock"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/conf"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/observability"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/postgres"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/server"
	"github.com/AustinZhu/quantum/datafeed/internal/infrastructure/validation"
	biz3 "github.com/AustinZhu/quantum/datafeed/internal/modules/content/biz"
	data3 "github.com/AustinZhu/quantum/datafeed/internal/modules/content/data"
	"github.com/AustinZhu/quantum/datafeed/internal/modules/ingestion/biz"
	"github.com/AustinZhu/quantum/datafeed/internal/modules/ingestion/data"
	biz2 "github.com/AustinZhu/quantum/datafeed/internal/modules/marketdata/biz"
	data2 "github.com/AustinZhu/quantum/datafeed/internal/modules/marketdata/data"
	"github.com/AustinZhu/quantum/datafeed/internal/modules/marketdata/service"
	biz4 "github.com/AustinZhu/quantum/datafeed/internal/modules/scanner/biz"
	data4 "github.com/AustinZhu/quantum/datafeed/internal/modules/scanner/data"
	service2 "github.com/AustinZhu/quantum/datafeed/internal/modules/scanner/service"
)

// Injectors from wire.go:

func InitializeAPIApp(ctx context.Context, configPath string) (*App, func(), error) {
	config, err := conf.New(ctx, configPath)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup, err := postgres.New(ctx, config)
	if err != nil {
		return nil, nil, err
	}
	outboxStore := postgres.NewOutboxStore(client)
	repository := data.NewRepository(client, outboxStore)
	v := clock.New()
	bizService := biz.NewService(repository, v)
	queryRepository := data2.NewQueryRepository(client)
	marketProvider := data2.NewMarketProvider(config)
	service3 := biz2.NewService(queryRepository, marketProvider)
	dataRepository := data3.NewRepository(client)
	service4 := biz3.NewService(dataRepository)
	datafeedHandler := service.NewDatafeedHandler(bizService, service3, service4)
	repository2 := data4.NewRepository(client)
	service5 := biz4.NewService(repository2, service3)
	handler := service2.NewHandler(service5)
	connectHandlerOptions, err := auth.New(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	observabilityConnectHandlerOptions, err := observability.New()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	validationConnectHandlerOptions, err := validation.New()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	serveMux := server.NewMux(datafeedHandler, handler, connectHandlerOptions, observabilityConnectHandlerOptions, validationConnectHandlerOptions, config)
	httpServer := server.NewHTTPServer(config, serveMux)
	app := New(httpServer, client)
	return app, func() {
		cleanup()
	}, nil
}
