CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE SCHEMA IF NOT EXISTS algorand;
CREATE SCHEMA IF NOT EXISTS datafeed;
CREATE SCHEMA IF NOT EXISTS doordash;

SELECT 'CREATE DATABASE temporal'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'temporal')\gexec
